cacheFolder: ./.yarn/cache

compressionLevel: mixed

enableGlobalCache: false

enableMirror: true

enableTelemetry: false

nodeLinker: pnp

patchFolder: ./.yarn/patches

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
